-- phpMyAdmin SQL Dump
-- version 4.9.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Dec 09, 2020 at 03:43 PM
-- Server version: 5.6.49-cll-lve
-- PHP Version: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `csci3632`
--

-- --------------------------------------------------------

--
-- Table structure for table `FGO`
--

CREATE TABLE `FGO` (
  `SERVANTID` int(11) NOT NULL,
  `NAME` text NOT NULL,
  `CLASS` text NOT NULL,
  `BIO` text NOT NULL,
  `SINGULARITY` text NOT NULL,
  `imageurl` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `FGO`
--

INSERT INTO `FGO` (`SERVANTID`, `NAME`, `CLASS`, `BIO`, `SINGULARITY`, `imageurl`) VALUES
(1, 'Mash Kyrielight', 'Shielder', 'This is Chaldea staff, Mash Kyrielight.\r\nAfter her Possessive Fusion with a Servant, she\'s called a Demi-Servant.', 'Fuyuki, Orleans, Septem, Okeanos, London, E Pluribus Unum, Camelot, Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2019-01/001_Mash_4Star.png?itok=V6S2QSKz'),
(2, 'Altria Pendragon (Alter)', 'Saber', 'Corrupted by the curse of the Holy Grail, this is the merciless side of the King of Knights. Or perhaps this is the true nature of the \"Ideal King\" that King Arthur sought to be. Altria controlled her own power and held back, but in this state, she wields her immense power without hesitation.', 'Fuyuki', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/VSowRz8.png?itok=N3tEcEre'),
(3, 'Nero Claudius', 'Saber', 'Despite being selfish and self-supremacist, she is cheerfully openhearted, an almighty, self-indulgent emperor who was loved by the people due to her child-like innocence. Her real name is Nero Claudius Caesar Augustus Germanicus. The Fifth Emperor of the Roman Empire.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/005%20Nero%20Claudius%20icon.png?itok=ymXg884l'),
(4, 'Siegfried', 'Saber', 'The hero matching a thousand, admired in the \"Nibelungenlied\". With the holy sword Balmung in hand, the \"dragon slayer\" who defeated the evil dragon Fafnir. Although taciturn, his passions run deep. In the battlefield, he is constantly on the front lines protecting his comrades.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/006%20Siegfried%20icon.png?itok=-XzJfxvX'),
(5, 'Gaius Julius Caesar', 'Saber', 'One of the greatest heroes of Ancient Rome.\r\nAn outstanding sovereign and a general that made a name for himself in the Galian Wars and the Britannia Expedition. A descendant of the goddess Venus, he supposedly fathered children with both humans and fairies alike.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/007%20Gaius%20Julius%20Caesar%20icon.png?itok=YXJP3t29'),
(6, 'Altera', 'Saber', 'A great king who established a great empire. Attila the Hun. A descendant of the Xiongnu (Hunnu), she is a warrior and king of the Hun tribe. A great hero from the 5th Century who controlled a vast territory, spanning from West Asia to Russia, Eastern Europe, and Gaul. It can be said that he invited the collapse of the Eastern Roman Empire.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/008%20Altera%20icon.png?itok=61NAxrbV'),
(7, 'Gilles de Rais (Saber)', 'Saber', 'French nobleman and soldier. Vaunted as a hero for taking Orleans along with the holy maiden Jeanne d\'Arc in the Hundred Year War, he is uptight yet valorous. For his acts he was given the title of marshal, the highest honor for any soldier.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/009%20Gilles%20de%20Rais%20%28Saber%29%20icon.png?itok=rwSOXQ5J'),
(8, 'Chevalier d\'Eon', 'Saber', 'A legendary individual from the 18th, 19th Century France, described as a feminine man or a masculine woman. Accomplished in both literary and military arts.\r\nWorked as a spy for the French intelligence \r\nagainst many powerful nations, and also served as an ambassador and dragoon regiment commander.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2019-12/010%20Chevalier%20dEon%20icon.png?itok=WThQXfUQ'),
(9, 'Gilgamesh', 'Archer', 'Before the Modern Era, this demigod king governed the Sumerian city-state of Uruk. The king described in mankind\'s oldest epic poem, the \"Epic of Gilgamesh\", he is considered to have existed not only in legends, but also in reality.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/012%20Gilgamesh%20icon.png?itok=toatDHS4'),
(10, 'Robin Hood', 'Archer', 'A faceless, nameless, chivalrous thief.\r\nAs he says himself, this young man is only one of the many \"someones\" that fit under the description of Robin Hood. The original legend is of the chivalrous thief hiding in Sherwood Forest. Originally Robin Hood stood against the tyrant John Lackland, but it is said he bled to death in the Kirkless Monastery due to a conspiracy involving the abbess.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/013%20Robin%20Hood%20icon.png?itok=ALhCdTTq'),
(11, 'Atalante', 'Archer', 'A famous female hunter from Greek mythology. Famous for being the first to land a shot during the Calidonian Boar hunt. She was also a member of the Argonautai, a group which housed every hero in Greece.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/014%20Atalante%20icon.png?itok=7Sb6kDDf'),
(12, 'Euryale', 'Archer', 'The middle daughter of the Gorgon Sisters in Greek mythology. The epitome of men\'s desires, she is the perfect \"idol.\" A goddess that was born as the \"ideal maiden.\" Her beauty is like innocence and purity were put into human form. Stheno is her elder sister and Medusa is her younger.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/015%20Euryale%20icon.png?itok=4OBY4F59'),
(13, 'Arash', 'Archer', 'The legendary hero of ancient Persia. As a warrior for King Manuchehr, who is dubbed the final king of ancient West Asia, he ended the war between the Persians and Turks that lasted 60 years. He is the hero of salvation that gave both peoples peace and tranquility.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/016%20Arashi%20icon.png?itok=6kjicCpJ'),
(14, 'Elizabeth Bathory', 'Lancer', 'The Countess of blood that became the model for the vampire Carmilla, or it should have been, but what was summoned as a Servant was her 14-year-old self from before she had committed any crimes. A sweet-type Servant who calls herself an idol. Noble, high-handed, cruel, merciless - she displays inhuman manners just like in legends.', 'Orleans, Septem, E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/018%20Elizabeth%20Bathory%20icon.png?itok=utewwHox'),
(15, 'Musashibou Benkei', 'Lancer', 'The most famous monk in Japanese history, who earned his fame with Minamoto-no-Yoshitsune. Even today, he is loved in various stories told through Kabuki and Joruri. Many phrases stem from him, such as Benkei\'s guardian stance (standing firm with feet apart), or Benkei\'s Crying Spot (that point below the knee on the calf).', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/019%20Musashibou%20Benkei%20icon.png?itok=3NnBAxQx'),
(16, 'Leonidas', 'Lancer', 'The King of Sparta, the country where the term \"Spartan education\" originated. In order to stop the invasion of one hundred thousand Persians, he took only three hundred men in the famous Battle of Thermopylae.', 'Septem, Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/021%20Leonidas%20icon.png?itok=fQTmP0Bv'),
(17, 'Romulus', 'Lancer', 'The nation-building hero that appears in Roman mythology. Born of the war-god Mars and the beautiful princess Silvia, he was raised by a divine wolf. He is the nation-building king that merged several nation-states in the Mediterranean to form the cornerstone of the glorious great Roman Empire. The Crimson Divine Father.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/022%20Romulus%20icon.png?itok=s8cybAND'),
(18, 'Georgios', 'Rider', 'A well-known saint by the name of Saint George, or Georgios. He\'s known for killing a dragon with the sacred sword Ascalon. He mounts a horse, Bayard, that can negate an enemy attack once.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/024%20St%20George%20icon.png?itok=VqscTpxB'),
(19, 'Edward Teach', 'Rider', 'The most well-known pirate in the world, and a scoundrel who most likely solidified the concept of pirate in the public consciousness. He conquered the Caribbean Sea, drunk on rum, women, and violence. He also accrued a massive fortune.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/025%20Edward%20Teach%20icon.png?itok=3-a7Q5Z6'),
(20, 'Boudica', 'Rider', 'The young Queen of ancient Britannia in the 1st century. Unable to forgive the Roman Empire after their vicious invasion which disgraced herself and her daughters, she rallied the kings into a rebellion, but ultimately lost her life when Emperor Nero\'s army crushed them. Later, she became known as the \"Queen of Victory.\" She is one of Britain\'s many legends.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/026%20Boudica%20icon.png?itok=P-FUpI_Z'),
(21, 'Ushiwakamaru', 'Rider', 'A military commander with a story so tragic you could say everyone in Japan knows her name. Although she was gifted with both talent and charisma, she was abandoned by her brother, Yoritomo, and was defeated along with her retainers including Benkei.\r\nUshiwakamaru was the childhood name of Minamoto-no-Yoshitsune.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/027%20Ushiwakamaru%20icon.png?itok=ce8rJg0N'),
(22, 'Alexander', 'Rider', 'In the 4th century BC, he was the young prince of Macedonia. A young boy with no equal, he was discovered by various wise men, starting with the philosopher Aristotle, to be a genius. A simple boy that loved the Iliad from the bottom of his heart, he was the manifestation of possibility itself.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/028%20Alexander%20icon.png?itok=Ashtss2F'),
(23, 'Marie Antoinette', 'Rider', 'The Queen of France born into the House of Habsburg. The Fleeting Lady. She is queen to the 18th century king, Louis XVI. She is the symbol of the rule of European nobility over the people. As society changed and the royals lost their authority, she lost her life before she could witness the change.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/029%20Marie%20Antoinette%20icon.png?itok=mKFd2HJE'),
(24, 'Saint Martha', 'Rider', 'A holy maiden, a saint, who calmed the evil dragon, Tarasque. Led by the words of the Messiah, along with her brother and sister, she became a person of unshakable faith. She was perfect, abundant in charm and beauty. A holy maiden who was able to charm such terrifying beast.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/030%20St%20Martha%20icon.png?itok=Y3DWmHva'),
(25, 'Gilles de Rais', 'Caster', 'A French noble from the 15th Century.\r\nHaving repeatedly committed the deed of abducting young boys from the vicinity of his domains and then disgracing and slaughtering them one after the other, things reached the point in which he became known as the model for the later fairytale \"Bluebeard\".', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/032%20Gilles%20de%20Rais%20%28Caster%29%20icon.png?itok=Jskeqz8u'),
(26, 'Hans Christian Andersen', 'Caster', 'One of the world\'s great three fairy tale authors. \"The Little Mermaid\" and \"The Little Match Girl\" were known throughout the world. Born in 1805, he died in 1875 from liver cancer. He\'s known as one of the great three authors now, but during his life he suffered constant setbacks with frustrations and failure.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/033%20Hans%20Christian%20Andersen%20icon.png?itok=uLqnAz6E'),
(27, 'William Shakespeare', 'Caster', 'William Shakespeare is definitely the most renowned playwright and actor. His name, which is highly praised in the world of English literature, is probably one of the most recognized names on this planet.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/034%20William%20Shakespeare%20icon.png?itok=CrIldMRB'),
(28, 'Wolfgang Amadeus Mozart', 'Caster', 'A world renowned composer and a performer.\r\nHe lived in the 18th century, and possessed a sense of sound that\'s out of this world. He left us with many wonderful scores, and was loved by God. A miraculous genius.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/036%20Wolfgang%20Amaedus%20Mozart%20icon.png?itok=4zpsYYIq'),
(29, 'Zhuge Liang (El-Melloi II)', 'Caster', 'Lord El-Melloi II originally didn\'t possess the capacity or the history to become a Servant. But due to the extremely special circumstances of this Holy Grail War, he was successfully summoned as a vessel for Zhuge Liang, a Heroic Spirit from ancient China.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/037%20Zhuge%20Liang%20%28El-Melloi%20II%29%20icon.png?itok=NbjCflEC'),
(30, 'Cu Chulainn (Caster)', 'Caster', 'A brave warrior from Celtic, Ulster mythology. A member of the Knights of the Red Branch and the strongest warrior in Ulster, at the same time that he is a hero that employs the magic spear received from the leader of the underworld Scáthach, he is also said to be a practitioner of runes - the magecraft of Northern Europe that was inherited from his mentor.', 'Fuyuki', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/038%20Cu%20Chulian%20%28Caster%29%20icon.png?itok=mJPYYz_4'),
(31, 'Hassan of the Cursed Arm', 'Assassin', 'A skeletal assassin. The leader of a cult of assassins based in the Middle East. AKA \"The Old Man of the Mountain.\" One of the leaders of the legendary group of Nizari whose name would later become the root word for the English \"assassin.\" There are 19 Old Men of the Mountain, each with their own abilities.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/040%20Cursed%20Arm%20Hassan%20icon.png?itok=gJb8HoSm'),
(32, 'Stheno', 'Assassin', 'The eldest of the three Gorgon sisters in Greek mythology. The epitome of what men long for, the perfect \"idol.\" A goddess that was born as the \"perfect woman.\" A beautiful woman as if elegance and refinement were put into human form. Euryale and Medusa are her younger sisters.\r\n\r\n', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/041%20Stheno%20icon.png?itok=xGp_LcUQ'),
(33, 'Jing Ke', 'Assassin', '...Ten steps left, I\'ll make sure to kill you. Jing Ke was an assassin who plotted the death of the First Emperor of China, and was one step shy of accomplishing it. If she hadn\'t been stopped, she may have rewritten the entire history of China.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/042%20Jing%20ke%20icon.png?itok=tYO6nLQq'),
(34, 'Charles-Henri Sanson', 'Assassin', 'The fourth head of the Sanson House that served as the executioner in Paris for generations. In the tumultuous times known as the French Revolution, he executed people of various social classes. With the introduction of the \"guillotine\" he further increased his number of executions.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/043%20Charles-Henri%20Sanson%20icon.png?itok=cR3yZhr9'),
(35, 'Phantom of the Opera', 'Assassin', 'Most likely the model for the figure...the Phantom that appeared in the novel \"The Phantom of the Opera\" that took place in the 19th century. Living in the vast labyrinth of aqueducts beneath the opera house, he was attracted to a young actress and helped her become a diva. But he committed a series of murders, so his love could never come to fruition.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/044%20Phantom%20of%20the%20Opera%20icon.png?itok=fer8x3jj'),
(36, 'Carmilla', 'Assassin', 'But, nobody told me! Nobody told me that this was a mistake! That is why I have become this way! Ah, my True Name is...Elisabeth Báthory!', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/046%20Carmilla%20icon.png?itok=pxW3qiXd'),
(37, 'Heracles', 'Berserker', 'One of the great heroes from Greek mythology. A demigod hero born from the union between the chief god Zeus and a human girl. Many adventures unfolded from his discord with the goddess Hera, and this superhuman overcame them all.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/047%20Heracles%20icon.png?itok=71Rconaf'),
(38, 'Lancelot', 'Berserker', 'The \"Knight of the Lake\", admired as the strongest even among the Knights of the Round Table. His adulterous love with Queen Guinevere invited the ruin of Camelot - surely, an individual who is the negative symbol of Arthurian Legends.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/048%20Lancelot%20icon.png?itok=lVDDIVai'),
(39, 'Lu Bu Fengxian', 'Berserker', 'The general of recurrence from the Romance of the Three Kingdoms. Twice he slew his foster fathers, and committed treachery over and over again on countless occasions - an unbelievable conduct in the China that prized Confucian morals. Still, his military exploits, deeds of arms are unmatched and he was counted as one of the strongest in the world of the Three Kingdoms.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/049%20Lu%20Bu%20icon_0.png?itok=F5VTwX_x'),
(40, 'Spartacus', 'Berserker', '--That man was pure muscle.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/050%20Spartacus%20icon.png?itok=W_RSF2wU'),
(41, 'Sakata Kintoki', 'Berserker', 'One of the big four of Minamoto no Raiko?, the strongest mystic killer of the Heian Period. Possessing the childhood name of \"Kintarou\", his popularity in Japan stands in line with Momotarou. A rowdy, insolent and dangerous man but-- in fact, he is righteous, honorable fellow with deep passions. He likes to say gold and golden all the time. His favorite dog is the Golden Retriever.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-08/vOh0IP7.png?itok=CvdVyoIO'),
(42, 'Vlad III', 'Berserker', 'Vlad III is a king of Romania and a hero.\r\nOriginally he would be summoned as a Lancer, but in this Holy Grail War he was summoned as a Berserker. An incarnation of calamity that mercilessly wields his powers as a vampire.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/052%20Vlad%20III%20icon.png?itok=qE5wnRBw'),
(43, 'Asterios', 'Berserker', 'Asterios - a monster (hero) bestowed with the name of lightning, but he was almost never called by that name. His alias that was widely spread over the world is Minotauros, which means bull of King Minos.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/053%20Asterios%20icon.png?itok=R276DOll'),
(44, 'Mephistopheles', 'Caster', 'Alas, the demon! The demon! The demon has come! Is Mephistopheles! That worst of all demons!', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/035%20Mephistopheles%20icon.png?itok=TS53nx0d'),
(45, 'Caligula', 'Berserker', 'Possessing legends of atrocity, the Third Emperor of the Ancient Roman Empire. An individual from the 1st Century. Uncle of Emperor Nero. At first, he was loved by the people as a wise ruler, until all of a sudden he became loved by the moon - falling into madness. In the few years until his assassination, he ruled the Empire through fear.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/054%20Caligula%20icon.png?itok=FB-TIKyc'),
(46, 'Darius III', 'Berserker', 'A valorous king of Ancient Persia. A character from the 4th Century BC. Known as the last king of Achaemenid Dynasty. A \"worthy rival\" of Iskandar, the King of Conquerors of Macedonia, and who had blocked his way for many times.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/055%20Darius%20III%20icon.png?itok=zTSxiJaH'),
(47, 'Kiyohime', 'Berserker', 'Beloved, so missed, beloved, so missed, betrayed, so sad, so sad, so sad, so sad, so sad, so hateful, so hateful, so hateful, so hateful, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate, hate,\r\nhate, hate, hate, hate, hate, hate, hate, hate, hate, hate. So I burned him to death.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/056%20Kiyohime%20icon.png?itok=bZ1tRvJN'),
(48, 'Eric Bloodaxe', 'Berserker', 'A Viking king who possesses a bloodied axe. That is Eric Bloodaxe. Also called \"Bloodaxe King\".', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/057%20Eric%20Bloodaxe%20icon.png?itok=i-sgtsFx'),
(49, 'Tamamo Cat', 'Berserker', 'One of the Tamamo-Nine. After Tamamo no Mae raised her divinity by means of 1,000 years of training, she cut loose eight tails so to return to her former one-tail self. Each and every one of them acquired divinity and transformed into Heroic Spirits as split-spirits. The crystallization of the (relatively) sincerely pure side that Tamamo no Mae possesses.', 'Septem', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-07/058%20Tamamo%20Cat%20icon.png?itok=W8Ntt7SD'),
(50, 'Jeanne d\'Arc', 'Ruler', 'O Lord, I dedicate this body to you----.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2019-12/059%20Jeanne%20dArc%20icon.png?itok=-mkGqSTw'),
(51, 'Orion', 'Archer', 'Artemis was summoned while having Orion as an accessory. Correction, it\'s the opposite. Upon summoning Orion, a hero of Greek Mythology, for some reason the goddess Artemis also came along. To make matters worse, Orion completely changed into a strange creature (mascot character) that cannot be defined as either a person nor a beast.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-08/060%20Artemis%20icon.png?itok=hkeBDx53'),
(52, 'David', 'Archer', 'David is a king of Israel that appears in the Old Testament. Originally a shepherd, he announced his candidacy to the one-on-one duel with the giant Goliath and defeated him. It has been said that afterwards - although there were a few quarrels with the king of that time - upon being splendidly enthroned as king, he carried out an excellent reign.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/David_Icon.png?itok=dEFYYysQ'),
(53, 'Hektor', 'Lancer', 'In the Trojan War, Hector was the supreme hero of the Trojan side. In face of overwhelming difference of soldiers, he maintained the siege by all means. Some even regard that, if it wasn\'t by Achilles, the war could have ended with the victory of the Trojans.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-09/Hector.png?itok=ghVtpTHk'),
(54, 'Francis Drake', 'Rider', 'An adventurer, a privateer, and commander of a fleet. Through the profits reaped from her circumnavigation of the world, England came to dominate the Age of Discovery. Furthermore, she sunk the powerful Spanish Invincible Armada, virtually crushing Spain - once called the Empire on which the Sun never set - and became known as \"the woman who sunk the Sun\".', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/FrancisDrake_Icon.png?itok=0LMfjLtz'),
(55, 'Anne Bonny & Mary Read', 'Rider', 'Anne Bonny and Mary Read are female pirates who existed during the Golden Age of Piracy. Having met by chance, the two endeavored as pirates under the command of captain John Rackham. It has been said that Anne was an expert of the rifle, while Mary was in charge of raiding with a cutlass.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-07/AnneMary_Icon.png?itok=x13T977Q'),
(56, 'Medea (Lily)', 'Caster', 'The queen of Colchis, Medea, summoned as the young girl Medea, from before she was called a \"witch\". Pure and innocent, as a lovely girl she has no vestiges of the \"Witch of Colchis\" yet.', 'Okeanos', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/MedeaLily_Icon.png?itok=y1nPmBrH'),
(57, 'Scathach', 'Lancer', 'A warrior-queen from Celtic - Ulster mythology. The queen and gatekeeper of the foreign territory - haunted realm called \"Land of Shadows\", a prodigy of spearmanship and Rune magic. Possesses a power immense enough to rule and close the gate of the \"Land of Shadows\", which is overflowing with countless ghosts. It has been said that she became the mentor of Cu Chulainn - who would later grow into the hero of Ulster - guiding him, teaching all sorts of techniques and even bestowing his favorite magic spear. She also instructed his son, Connla.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-11/Scathachicon.png?itok=q0CsApi8'),
(58, 'Diarmuid Ua Duibhne', 'Lancer', 'Celt mythology. Under the command of the leader Fionn, he was a prominent Knight of the Knights of Fianna and the owner of a beautiful face. Possessing a dark mole on his cheek conferred by a fairy, it carried a magical power that made the hearts of young maidens flutter.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-11/Icon_Servant_071.png?itok=rwzEfp7c'),
(59, 'Fergus mac Roich', 'Saber', 'A brave warrior from the Celtic, Ulster era (Cycle). A member of the Knights of the Red Branch, a magic sword-user that is also known as the friend and foster father of the hero Cú Chulainn. A great glutton that possessed matchless vigor, great generosity, who didn\'t feel envy nor fear-- even now, Fergus\' reputation as a magnificent and brave warrior has been left for posterity.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-11/Icon_Servant_072.png?itok=GFKMU0ii'),
(60, 'Nursery Rhyme', 'Caster', '\"Nursery Rhyme is a nursery song. Tommy Thumb\'s cute picture book. The initial form of Mother Goose. The sorrowful me to the lonely you. Lets us grant those last wishes.\"', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-11/Icon_Servant_074.png?itok=ZaWvzJp_'),
(61, 'Jack the Ripper', 'Assassin', 'A serial-killer whose name is known all over the world. In Japan, it is often designated as \"Jack the Ripper\" without change. In spite of the frantic investigations of the Scotland Yard, it butchered five women and then disappeared without ever getting caught.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/JacktheRipper_Icon.png?itok=FGU5sIbC'),
(62, 'Mordred', 'Saber', 'Mordred is a Knight of the Round Table and the legitimate child of King Arthur. At the same time, the one who put an end to the legend-- at Camlann Hill, the Knight of Rebellion who slew King Arthur.', 'London, Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-11/Icon_Servant_076.png?itok=dNeEuLCi'),
(63, 'Nikola Tesla', 'Archer', 'A genius scientist from the 19th~20th Century who controlled electromagnetism.\r\nA brazen prodigy, who proclaimed that he could even split the Earth in two. One of the great scholars who clarified the power of thunder and lightning, which is described in many mythologies as a legend of god (nature), bringing about \"electricity\" to human civilization.', 'London, E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-12/Icon_Servant_077.png?itok=qcx5oiuM'),
(64, 'Altria Pendragon (Lancer Alter)', 'Lancer', 'The King of Knights of the Round Table that is described in legends. In reality, a lovely female-knight, and yet possesses both purity and integrity just like in legends. She is known as a holy sword-user, but the holy spear she possesses is actually quite powerful as well, making it possible to manifest as a Lancer. Furthermore, it is also possible for her to materialize as the possibility of having been corrupted by the curse of the Holy Grail like this. The spear-wielding aspect of the King of Knights that persists in being heartless.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-12/Icon_Servant_078.png?itok=W66tJX_e'),
(65, 'Paracelsus von Hohenheim', 'Caster', 'A legendary physician turned alchemist. In the 16th Century, he is known as a character from the Renaissance Period. He left behind many achievements and books such as the \"rediscovery of the four (five) elements\" and the \"rediscovery of the three senses of humor\". A rare individual who went down in both human and magic history.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-12/Icon_Servant_079.png?itok=i6gTrtj4'),
(66, 'Charles Babbage', 'Caster', 'A mathematician turned scientist from the 19th Century. The King of Steam who dreamed about the revolution of the world. The prodigious great scholar who employed a steam engine to invent the first computers in the world - the \"Difference Engine\" and the \"Analytical Engine\". In modern times, he came to be called a \"father of the computer\".', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-12/Icon_Servant_080.png?itok=Ft4_J2Ld'),
(67, 'Henry Jekyll & Hyde', 'Assassin', 'A character of the 19th-century novel, \"Dr. Jekyll and Mr. Hyde\" or rather, the person whom the character was modeled after. He tried to detach the \"evil\" from his personality but ended up revealing a personality that embodied that \"evil\" and eventually came to commit murder, bringing his own ruin in the end.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-12/Icon_Servant_081.png?itok=b0XIpTPM'),
(68, 'Frankenstein', 'Berserker', 'The artificial life form created by Victor Frankenstein. Built as the Eve that forms a pair with Adam, because her expressing of human emotions does not function well, she was branded a failure.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-12/Icon_Servant_082.png?itok=a6eOxxxu'),
(69, 'Arjuna', 'Archer', 'A great hero from the ancient epic poem from India, \"Mahabharata\". The Mahabharata is a dazzling story that gathers all heroes from India, but it is no exaggeration to say that Arjuna is an existence placed at the center of it all.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Arjunaicon.png?itok=gL8HrYhA'),
(70, 'Karna', 'Lancer', 'A great hero from the ancient epic poem from India, \"Mahabharata\". The rival of Arjuna, the central hero of the Mahabharata, as well as his half-brother by a different father. Upon becoming unable to move due to many curses, he was brought down by Arjuna in a manner similar to deliberate murder.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Karnaicon.png?itok=zAQpQ2Pn'),
(71, 'Fionn mac Cumhaill', 'Lancer', 'A descendant of the Celtic War God Nuada and the leader of the glorious Knights of Fianna. A great hero that established many valorous deeds - such as saving the capital by defeating an wicked Divine Spirit that manipulated flames and sleep, or defeating invaders and monsters as the guardian of Erin (Ireland). Having mastered magecraft and wisdom, originally he would be endowed with many abilities and Noble Phantasms.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Fionnicon.png?itok=J3_ctr8e'),
(72, 'Beowulf', 'Berserker', 'Beowulf is the protagonist of \"Beowulf\", said to be the oldest epic poem of English literature. The setting of the epic poem amounts to south of modern Sweden to the vicinity of Denmark.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Beowulficon.png?itok=dkX8lipq'),
(73, 'Nero Claudius (Bride)', 'Saber', 'With a whole new get-up, the emperor of roses wrapped herself in a pure white outfit. Due to the exchange of outfit, her tension has also changed and her combat-style underwent a variation from its original condition. Even her favorite sword - Original Fire - has read the mood and converted its blade from red to silvery snow.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Brideicon.png?itok=5FPh-XSl'),
(74, 'Nightingale', 'Berserker', 'The angel of Crimea that makes attendance and dedication into her creed. A woman of conviction. Owner of a tenacious mentality that never becomes disheartened and say words which should be said to whoever it is - even the monarch of the British Empire. Her nickname is \"Little War Office\". Owner of a persistence that could also be described as a one woman army. Due to her present manifestation she is in a condition in which said mentality is combined with an EX Madness Enhancement skill, unlike what she was in life (probably), \"she does not listen to people at all\".', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Nightingaleicon%20%281%29.png?itok=HwRxHCzl'),
(75, 'Cu Chulainn (Alter)', 'Berserker', 'The legendary warrior of the Ulster Cycle of Celtic mythology. A member of the Red Branch Knights and the strongest fighter of Ulster, he won his fame with his mastery of the invincible spear techniques taught to him by Scathach, the ruler of the alternate realm called the Land of Shadows. He has unusually taken form as a Berserker. Some factor of his summoning also caused all of his equipment to change and reversed his temperament. His expressions become cold, and the crimson demonic spear that is his Noble Phantasm has been mixed with darkness, overflowing with a foreboding aura.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/CuAltericon.png?itok=4oGl25iW'),
(76, 'Medb', 'Rider', 'The queen of Connacht that appears in Celtic Mythology, the Ulster Cycle. A young girl of affairs who built engagements, marriages and, at times, nothing but carnal relations with many kings and brave warriors. The eternal lady. The ringleader who caused the greatest war of the Ulster Cycle, she aimed at the life of the brave warrior of Ulster that defied her - Cu Chulainn.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Medbicon.png?itok=laFPKoxi'),
(77, 'Helena Blavatsky', 'Caster', 'A female occultist from the 19th Century, a founder of theosophy.\r\nDespite having married young to a Russian aristocrat, she soon eloped and then lived gorgeously in the magic world. Popularly known as Madame Blavatsky. She is considered to have immersed herself on mysticism out of belief in the existence of the Lemurian continent, eventually coming in contact with a higher existence (\"Mahatma\") and its collective body (\"Hierarchy\"*), acquiring many wisdoms in the process.\r\nIf that is indeed the case, she might have caught a glimpse of a possibility towards the Root.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Helenaicon.png?itok=J5Su9T6y'),
(78, 'Rama', 'Saber', 'The protagonist of the Ramayana, one of the two major epic poems from India. Ravana -who could enslave even the gods due to a power acquired by deceiving a great god - was a demon lord famed for the fact that only humans had the qualifications to defeat him. Granting the appeals of the gods, Vishnu reincarnated as the prince of a certain country; an ordinary human that had forgotten about everything. Such is Rama.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Ramaicon.png?itok=hv-meaxr'),
(79, 'Li Shuwen', 'Lancer', 'Li Shuwen in his prime, summoned as a Lancer. A legendary martial artist from China who, despite born in modern times, carved many legends. He is of course famous as a master of Baji Quan, but the exquisiteness of his spear-wielding is to the point of being extolled as \"God Spear\".', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/102%20Li%20Shuwen%20icon.png?itok=dMOMMnmT'),
(80, 'Thomas Edison', 'Caster', 'Thomas Alva Edison is an inventor originated from America. As a person born in the 19th Century, he boasts worldwide popularity, but his capacity as a Servant is somewhat inferior due to such modernity.\r\nIn order to compensate for that in this summoning, the successive generations of Presidents that supported the nation called America are being treated as a kind of Craft Essence that reinforces the concept called \"Edison\".', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/103%20Thomas%20Edison%20Icon.png?itok=arrO3YM_'),
(81, 'Geronimo', 'Caster', 'Geronimo is a warrior of the Apaches, one of the aboriginal people from the North American continent. Originally owner of a carefree name that meant \"the one who yawns\" in the Apache language, his life completely changed when he was 20 years old. Upon having his wife and children slaughtered by Mexican soldiers, he made a bold speech and carried out a revenge against the Mexican army as a \"warrior\".', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/104%20Geronimo%20Icon.png?itok=eKAUNDym'),
(82, 'Billy the Kid', 'Archer', 'Billy the Kid. His real name is William Henry McCarty Junior. A representative outlaw from the American Wild West, even in modern times his popularity is extremely high. From the fact that one of his few remaining pictures was put for a price of two billion dollars in an auction, one can perceive said popularity. His father is unknown, but it seems that he received a higher education from his mother and, considering he was a Western outlaw, he left behind some skillfully written letters.', 'E Pluribus Unum', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/105%20Billy%20the%20Kid%20Icon.png?itok=5NY3WFzr'),
(83, 'Jeanne d\'Arc (Alter)', 'Avenger', 'If God exists, then I will certainly receive divine punishment.', 'Orleans', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Jeannealtericon.png?itok=e6AMUZsF'),
(84, 'Hassan of the Hundred Personas', 'Assassin', 'One of the successive generations of the Old Man of the Mountain, Hassan. Because of a too wide-ranging abundance of knowledge and an inexplicable mentality with tendencies that nobody can predict, he was feared as the one of \"hundred visages\", but in truth he was a character who suffered from a mental disorder known today as multiple personality disorder.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/Icon_Servant_110.png?itok=yNvAfu65'),
(85, 'Xuanzang Sanzang', 'Caster', 'A Buddhist priest from the Tang dynasty, in the 7th Century AD. Traveling through the Silk Road in pursuit of the original Buddhist scriptures, she reached India from central Asia and then brought back to China over 367 sutras, becoming the founder of the Faxiang Buddhist sect.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Xuanzangicon.png?itok=igrLnrbl'),
(86, 'Ozymandias', 'Rider', 'A person from the 14th~13th Century BC. A pharaoh from ancient Egypt who governed over a vast empire. Like Osiris, he loved the masses, and was also greatly loved by the people. Also called Ramesses II, or Meryamen.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_118.png?itok=16Y6_hCi'),
(87, 'Altria Pendragon (Lancer)', 'Lancer', 'The legendary King of Knights who controlled Britain, King Arthur. A \"what if\" King Arthur who, after rising as a king, primarily used the holy spear instead of the holy sword and governed over Britain. Having lost the growth-halt from the holy sword, she grew to a physical age fitting for a king. She became an existence closer to Divine Spirits due to using the holy spear, but since the period of use was just that of ten-odd years, her mental structure and spiritual make-up has not changed too much.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_119.png?itok=SQuQKaB_'),
(88, 'Nitocris', 'Caster', 'A magic queen who held the throne during the Sixth Dynasty of ancient Egypt, even if only for a short while. Strangely enough, she has the same name as an ancient queen from Babylon. It has been assumed that she caused all influential men who deliberately murdered her beloved brothers to die by drowning, and then took her own life after accomplishing her revenge.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_120.png?itok=QngRZimD'),
(89, 'Lancelot (Saber)', 'Saber', 'Lancelot is one of the Knights of the Round Table and a hero extolled as the greatest knight. Despite serving King Arthur, he ended up breaking with the king upon falling into an immoral love with Guinevere.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_121.png?itok=F5Usq_kU'),
(90, 'Tristan', 'Archer', 'One of the Knights of the Round Table from Arthurian legends. His Class is Saber, but he is often summoned as an Archer due to his renown with a bow. The tale of Tristan and Iseult, the woman he loved, is a legend boasting outstanding popularity in Europe.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_122.png?itok=pAe1qCuH'),
(91, 'Gawain', 'Saber', 'One of the Knights of the Round Table from Arthurian legends. One of the longest-serving knights, a devoted knight who served until the conclusion of the king\'s fight. Possessing the holy sword of the sun, said to be Excalibur\'s sister-sword, he won fame as a peerless knight who was unmatched during daytime thanks to the blessings of a saint.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/Icon_Servant_123.png?itok=bI8urhE5'),
(92, 'Hassan of the Serenity', 'Assassin', 'An assassin that wears a skull mask.\r\nOne of the successive Hassan-i-Sabbah that played the role of Old Man of the Mountain - the leader of the assassination cult - it has been said that while alive she was an expert in poison and given the alias Hassan of Serenity.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/Icon_Servant_124.png?itok=W0nJxtDR'),
(93, 'Tawara Tota', 'Archer', 'A warrior from the mid-Heian period, Tawara Tota was revered as the founder of martial arts in the Kanto provinces. Later introducing himself as Fujiwara Hidesato, he suddenly won fame by shooting Taira Masakado. It has been told that he exterminated a great centipede - big enough to make seven and a half turns around a mountain - with a bow and arrow.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_125.png?itok=cVCk6dQd'),
(94, 'Bedivere', 'Saber', 'One of the Knights of the Round Table from Arthurian legends. The first member of the Knights of the Round Table, he served as the steward of the royal court, the king\'s care-taker. The individual who was present at the king\'s final moments.', 'Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_126.png?itok=b1Z1uxJq'),
(95, 'Leonardo Da Vinci', 'Caster', 'A genius referred to as almighty. An individual from 15th to 16th Century Europe. A prominent genius who caused much impact on the advance of civilization and carved his name on human history. He has been recorded as a peerless pretty boy, a peerless handsome young man, but this is the actual state of things. Before a true genius, gender and age are rendered meaningless. Doctrine and fashion may change with age, but there is only one truth. Whatever happens, Da Vinci-chan is the unrivaled almighty!', 'Fuyuki, Orleans, Septem, Okeanos, London, E Pluribus Unum, Camelot, Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/Icon_Servant_127.png?itok=x-w6uxCk'),
(96, 'Ishtar', 'Archer', 'A goddess of beauty, good harvests, and war from Mesopotamian mythology. Said to be the most pampered, or rather, most beloved goddess by the other deities. This form is not that of the goddess Ishtar herself, but a pseudo-Servant condition in which a human that has a wavelength close to her own was made into a vessel. She says that her role is to watch over humans in a way appropriate for a goddess, but that means to watch over while snickering. \"Well then, I wonder if humans will survive this, or will they be extinct?\" Truly, a (red) devil from Venus.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_142.png?itok=5poWDDYT'),
(97, 'Enkidu', 'Lancer', 'From their gentle tone and graceful bearings, one would never guess that this is a “Noble Phantasm with a will” that possesses a fierce combat power. The chains that fasten heavens and earth, regarded by the King of Heroes Gilgamesh as one of the strongest. A doll created by the hands of the gods, and also an offshoot of the earth that harmonizes and becomes one with nature. A tragic weapon that underwent many adventures as the sole friend of the King of Heroes and, after acquiring a human heart, returned to dirt as a doll.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-03/Icon_Servant_143.png?itok=eUiAId53'),
(98, 'Quetzalcoatl', 'Rider', 'One of the highest existences in Aztec Mythology, from Central and South America. Seemingly freewheeled, a goddess brimming with kind-hearted intelligence. She hated sacrificial ceremonies and loved humans. A deity of life and good harvests, a deity of culture, a deity of rain and wind. There are also legends of her governing over the sun for a period. The manifestation of a highest existence (by means of a Bunrei). Thanks to this abnormal circumstances, Quetzalcoatl drew a new face that nobody knows. That of a deity that loves the free fight that prospers in modern Mexico - lucha libre. It is not like she is being worshiped as a deity of lucha by the people in particular. She just likes lucha.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_144.png?itok=A9H0KMNL'),
(99, 'Gilgamesh (Caster)', 'Caster', 'The supreme wise king who returned from the journey of immortality. In legends, he has been described as “the one who saw everything”. At times ruthless, at times approving of human nature; the great king of Uruk that strictly lead the masses.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-09/Gilcastericon.png?itok=CJMZdww1'),
(100, 'Medusa (Lancer)', 'Lancer', 'The youngest of the Gorgon Sisters that appears in Greek Mythology. A goddess born as a perfected \"image (idol)\", the embodiment of men\'s longing. Due to some factor, the anti-hero Medusa acquired a condition as a goddess that is close to that of her two sisters and manifested as a Servant.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Icon_Servant_146.png?itok=GLKnM-_g'),
(101, 'Gorgon', 'Avenger', 'The youngest of the Gorgon Sisters that appears in Greek Mythology. Her original true name is Medusa. The mere shadow of a cursed growth. A condition in which, due to some factor, the monster disposition that is her foundation (original) was considerably emphasized. A stage that is on the verge of a complete metamorphosis from a goddess to the behemoth monster “Gorgon” and, originally, is not something that would be summoned as a Servant. An existence that might already be called the queen of magical beasts.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_147.png?itok=F8wayllU');
INSERT INTO `FGO` (`SERVANTID`, `NAME`, `CLASS`, `BIO`, `SINGULARITY`, `imageurl`) VALUES
(102, 'Jaguar Man', 'Lancer', 'A divine spirit of old handed down on Central and South America. The jaguar is, namely, a symbol of “war” and “death”, an existence revered for a long time on the Central and South American civilizations of all periods, and it has been said that, in the past, it would reveal itself to the world from time to time. In the Olmec civilization of the Preclassic Period, the jaguar deity was a mixed-blood of human and jaguar... Defined in the shape of a jaguar-human and the likes.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Icon_Servant_148.png?itok=Ya08cWNd'),
(103, 'Merlin', 'Caster', 'The vagrant of the paradise. The court mage, advisor and prophet that appears in Arthurian legends. He would at times guide, at times torment and at times help King Arthur so that she could overcome many enemies and hardships.\r\nStill, even as a wise man he is fundamentally inhuman. For you see, he is a mixed-blood of incubus and human. “I like the world of humans very much, but when it comes to each of them individually, I’m relatively, look, well, yeah! Very well, I suddenly feel that some things are better left unsaid!” Just like this, it is not like he is an ally of humans. One among the top-ranking Casters, but he himself does not treat magecraft as his forte. The reason being that he stumbles during incantations.', 'E Pluribus Unum, Camelot, Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-06/Icon_Servant_150.png?itok=FSBGukET'),
(104, 'First Hassan', 'Assassin', 'An assassin that wears a skull mask.\r\nRegarded as the first Hassan Sabbah, who was born when the name “Old Man of the Mountain” changed into a title, after the assassination cult became established as assassins. However, it has been said that neither the other 18 Hassans nor the followers of the cult knew this individual’s true identity and that no evidence that he truly existed could be found anywhere. He is a legendary assassin, said to appear to take the head of a generation’s Hassan-i-Sabbah when they stray from the path.\r\nIn other words, a Hassan that kills other Hassans.', 'Camelot, Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_154.png?itok=bsaREvlH'),
(105, 'Sherlock Holmes', 'Ruler', 'The world’s sole and greatest consulting detective. The crystallization of the concept of detective; the representative of “those who reveal”. The protagonist of the stories that Sir Arthur Conan Doyle wrote in the 19th~20th Century, he is a detective who explains all enigmas and one of the ancestors of the “detectives” that appear in the many mystery novels of later years—-- Or so it is assumed. But what is the truth, really?', 'London, Camelot', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-04/Icon_Servant_173.png?itok=JX4Vf2tU'),
(106, 'Ereshkigal', 'Lancer', 'The Goddess of the Netherworld in Sumerian myth. She freely wields a spear-like cage; at times stabbing the enemy with, at times imprisoning souls, at times summoning lightning, she is the fearsome ruler of the netherworld. Having carried out her duties of administrating the netherworld since birth, she is a goddess that disappeared along with the Age of Gods without ever knowing of the world above, or of freedom. This form is not that of the Goddess Ereshkigal, but that of a Pseudo-Servant where she has possessed the soul of a human with a similar wavelength to hers. Though she claims that her role is merely to supervise humans, like the netherworld goddess that she is... \"...it\'s a problem if so many people are coming to the netherworld... it\'s also a big issue creating cages to confine all these souls... I wonder if I can provide them a more comfortable place to be in...\"\r\nIn this way, it\'s hard to fully conceal her caring heart. She is truly a red angel of the netherworld.', 'Babylonia', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2018-08/196_Ereshkigal_Icon.png?itok=04Uj4z4J'),
(110, 'Tamamo-no-Mae', 'Caster', 'A good-wife-aspirant, extravagant miko shaman. In the deathbed of the Heian Period, this peerless beauty served the retired emperor Toba. It has been said that she is the disguised appearance of the nine-tailed fox Hakumen Kinmou. For a number of reasons, in the end she was chased away from the imperial court and, after having a major decisive battle with humans in the fields of Nasu, obediently let herself be exterminated, or something.', 'London', 'https://gamepress.gg/grandorder/sites/grandorder/files/styles/width50px/public/2017-09/MFiRy5d.png?itok=w_UZjcQg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `FGO`
--
ALTER TABLE `FGO`
  ADD PRIMARY KEY (`SERVANTID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `FGO`
--
ALTER TABLE `FGO`
  MODIFY `SERVANTID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=111;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
